#!/usr/bin/env bash
set -u

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${TIBO_LAUNCHER_CONFIG:-$SCRIPT_DIR/launcher.conf}"
FALLBACK_CHATGPT_BIN="${TIBO_FALLBACK_CHATGPT_BIN:-/usr/lib/chatgpt/ChatGPT}"

notify_failure() {
  local title="$1"
  local body="$2"
  if [[ -n "${TIBO_NOTIFY_BIN:-}" && -x "${TIBO_NOTIFY_BIN}" ]]; then
    "${TIBO_NOTIFY_BIN}" --app-name=Tibolution --urgency=critical -- "$title" "$body" >/dev/null 2>&1 || true
  elif command -v notify-send >/dev/null 2>&1; then
    notify-send --app-name=Tibolution --urgency=critical -- "$title" "$body" >/dev/null 2>&1 || true
  fi
}

fallback_launch() {
  if [[ -x "${TIBO_CHATGPT_BIN:-$FALLBACK_CHATGPT_BIN}" ]]; then
    exec "${TIBO_CHATGPT_BIN:-$FALLBACK_CHATGPT_BIN}" "$@"
  fi
  notify_failure "Tibolution could not start Codex Desktop" "The configured ChatGPT executable is unavailable."
  exit 1
}

if [[ ! -f "$CONFIG_FILE" || -L "$CONFIG_FILE" ]]; then
  fallback_launch "$@"
fi

# The config is generated by install-linux-launcher.sh in the same user-owned directory.
# shellcheck source=/dev/null
source "$CONFIG_FILE"

for required in TIBO_PROJECT_DIR TIBO_NODE_BIN TIBO_CHATGPT_BIN TIBO_TARGET_ASAR TIBO_DIST_DIR TIBO_PKEXEC_BIN TIBO_FLOCK_BIN; do
  value="${!required:-}"
  if [[ -z "$value" || "$value" != /* || "$value" == *$'\n'* ]]; then
    notify_failure "Tibolution self-check disabled" "The launcher configuration is invalid."
    fallback_launch "$@"
  fi
done

if [[ ! -x "$TIBO_NODE_BIN" || ! -x "$TIBO_CHATGPT_BIN" || ! -x "$TIBO_PKEXEC_BIN" || ! -x "$TIBO_FLOCK_BIN"
  || ! -f "$TIBO_TARGET_ASAR" || -L "$TIBO_TARGET_ASAR"
  || ! -f "$TIBO_PROJECT_DIR/scripts/platform.mjs"
  || ! -f "$TIBO_PROJECT_DIR/scripts/check-installed.mjs"
  || ! -f "$TIBO_PROJECT_DIR/scripts/prepare-install.mjs"
  || ! -f "$TIBO_PROJECT_DIR/scripts/transaction.mjs" ]]; then
  notify_failure "Tibolution self-check disabled" "A configured file is missing or unsafe; Codex will start without automatic repair."
  fallback_launch "$@"
fi

CACHE_ROOT="${XDG_CACHE_HOME:-${HOME:?HOME is required}/.cache}/tibolution"
if ! mkdir -p -- "$CACHE_ROOT" || ! chmod 700 -- "$CACHE_ROOT"; then
  notify_failure "Tibolution self-check disabled" "The per-user lock directory could not be created."
  fallback_launch "$@"
fi
LOCK_FILE="$CACHE_ROOT/desktop-launch.lock"
exec 9>"$LOCK_FILE"
if ! "$TIBO_FLOCK_BIN" -n 9; then
  exit 0
fi

launch_desktop() {
  "$TIBO_FLOCK_BIN" -u 9 >/dev/null 2>&1 || true
  exec 9>&-
  exec "$TIBO_CHATGPT_BIN" "$@"
}

last_message() {
  local text="$1"
  local line
  line="$(printf '%s\n' "$text" | sed -n '/[^[:space:]]/h;${x;p;}')"
  printf '%s' "${line:-Unknown error.}"
}

"$TIBO_NODE_BIN" "$TIBO_PROJECT_DIR/scripts/platform.mjs" running >/dev/null 2>&1
running_status=$?
if [[ $running_status -eq 10 ]]; then
  launch_desktop "$@"
elif [[ $running_status -ne 0 ]]; then
  notify_failure "Tibolution self-check skipped" "Desktop process detection failed; no files were changed."
  launch_desktop "$@"
fi

check_output="$("$TIBO_NODE_BIN" "$TIBO_PROJECT_DIR/scripts/check-installed.mjs" --target "$TIBO_TARGET_ASAR" 2>&1)"
check_status=$?
if [[ $check_status -eq 0 ]]; then
  launch_desktop "$@"
elif [[ $check_status -ne 20 ]]; then
  notify_failure "Tibolution compatibility check failed" "$(last_message "$check_output") Codex will start without automatic repair."
  launch_desktop "$@"
fi

PATCHED_ASAR="$TIBO_DIST_DIR/app.tibo-patched.asar"
build_output="$("$TIBO_NODE_BIN" "$TIBO_PROJECT_DIR/scripts/prepare-install.mjs" \
  --target "$TIBO_TARGET_ASAR" --patched "$PATCHED_ASAR" --dist "$TIBO_DIST_DIR" 2>&1)"
build_status=$?
if [[ $build_status -ne 0 ]]; then
  notify_failure "Tibolution could not adapt this Codex update" "$(last_message "$build_output") The official client was not changed."
  launch_desktop "$@"
fi

install_output="$("$TIBO_PKEXEC_BIN" "$TIBO_NODE_BIN" "$TIBO_PROJECT_DIR/scripts/transaction.mjs" install \
  --target "$TIBO_TARGET_ASAR" --patched "$PATCHED_ASAR" --dist "$TIBO_DIST_DIR" 2>&1)"
install_status=$?
if [[ $install_status -ne 0 ]]; then
  notify_failure "Tibolution automatic repair was not installed" "$(last_message "$install_output") Codex will start unchanged."
  launch_desktop "$@"
fi

if ! "$TIBO_NODE_BIN" "$TIBO_PROJECT_DIR/scripts/check-installed.mjs" --target "$TIBO_TARGET_ASAR" >/dev/null 2>&1; then
  notify_failure "Tibolution post-install check failed" "Codex will start, but the background patch could not be confirmed."
fi
launch_desktop "$@"
